
package gov.nist.registry.ws.serviceclasses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryRequest;
import oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "xdsregistrybPortType", targetNamespace = "http://serviceclasses.ws.registry.nist.gov")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.nist.registry.common2.exception.xsd.ObjectFactory.class,
    gov.nist.registry.common2.registry.xsd.ObjectFactory.class,
    gov.nist.registry.ws.serviceclasses.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.query._3.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rim._3.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rs._3.ObjectFactory.class
})
public interface XdsregistrybPortType {


    /**
     * 
     * @param body
     * @return
     *     returns oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse
     */
    @WebMethod(operationName = "AdhocQueryRequest", action = "urn:ihe:iti:2007:ns:AdhocQueryRequestRequest")
    @WebResult(name = "AdhocQueryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", partName = "body")
    public AdhocQueryResponse adhocQueryRequest(
        @WebParam(name = "AdhocQueryRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", partName = "body")
        AdhocQueryRequest body);

}
