
package gov.nist.registry.ws.serviceclasses;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "xdsregistryb", targetNamespace = "http://serviceclasses.ws.registry.nist.gov", wsdlLocation = Xdsregistryb.REGISTRY_PATH)
public class Xdsregistryb
		extends Service {

	public final static String REGISTRY_PATH = "RegistryPS_1.wsdl";
	private final static URL XDSREGISTRYB_WSDL_LOCATION;
	private final static WebServiceException XDSREGISTRYB_EXCEPTION;
	private final static QName XDSREGISTRYB_QNAME = new QName("http://serviceclasses.ws.registry.nist.gov", "xdsregistryb");

	static {
		WebServiceException e = null;
		XDSREGISTRYB_WSDL_LOCATION = Xdsregistryb.class.getResource(REGISTRY_PATH);
		if (XDSREGISTRYB_WSDL_LOCATION == null) {
			e = new WebServiceException("Cannot find 'registry.wsdl' wsdl. Place the resource correctly in the classpath.");
		}
		XDSREGISTRYB_EXCEPTION = e;
	}

	public Xdsregistryb() {
		super(__getWsdlLocation(), XDSREGISTRYB_QNAME);
	}

	public Xdsregistryb(WebServiceFeature... features) {
		super(__getWsdlLocation(), XDSREGISTRYB_QNAME, features);
	}

	public Xdsregistryb(URL wsdlLocation) {
		super(wsdlLocation, XDSREGISTRYB_QNAME);
	}

	public Xdsregistryb(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, XDSREGISTRYB_QNAME, features);
	}

	public Xdsregistryb(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Xdsregistryb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return
	 * 		returns XdsregistrybPortType
	 */
	@WebEndpoint(name = "xdsregistrybHttpSoap12Endpoint")
	public XdsregistrybPortType getXdsregistrybHttpSoap12Endpoint() {
		return super.getPort(new QName("http://serviceclasses.ws.registry.nist.gov", "xdsregistrybHttpSoap12Endpoint"), XdsregistrybPortType.class);
	}

	/**
	 *
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default
	 *            values.
	 * @return
	 * 		returns XdsregistrybPortType
	 */
	@WebEndpoint(name = "xdsregistrybHttpSoap12Endpoint")
	public XdsregistrybPortType getXdsregistrybHttpSoap12Endpoint(WebServiceFeature... features) {
		return super.getPort(new QName("http://serviceclasses.ws.registry.nist.gov", "xdsregistrybHttpSoap12Endpoint"), XdsregistrybPortType.class, features);
	}

	private static URL __getWsdlLocation() {
		if (XDSREGISTRYB_EXCEPTION != null) {
			throw XDSREGISTRYB_EXCEPTION;
		}
		return XDSREGISTRYB_WSDL_LOCATION;
	}

}
